name: Github Pages

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: install GHC and cabal
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.0.2'
        cabal-version: '3.8.1.0'

    - name: Caching build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Install YST
      run: |
        cabal update
        cabal install yst

    - name: Generate Site
      run: /home/runner/.cabal/bin/yst

    - name: push to gh_pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh_pages
        
    - name: Setup Pages
      uses: actions/configure-pages@v2
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./site"
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write     
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
